version: '3'

volumes:
  postgres_data:
      driver: local
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "jobQueue:1:1, jobStatus:1:1"
  # postgres:
  #     image: postgres
  #     volumes:
  #       - postgres_data:/var/lib/postgresql/data
  #     environment:
  #       POSTGRES_DB: keycloak
  #       POSTGRES_USER: keycloak
  #       POSTGRES_PASSWORD: password
  # keycloak:
  #     image: quay.io/keycloak/keycloak:20.0.3
  #     environment:
  #       DB_VENDOR: POSTGRES
  #       DB_ADDR: postgres
  #       DB_DATABASE: keycloak
  #       DB_USER: keycloak
  #       DB_SCHEMA: public
  #       DB_PASSWORD: password
  #       KEYCLOAK_ADMIN: ADMIN
  #       KEYCLOAK_ADMIN_PASSWORD: 1234
  #       # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
  #       #JDBC_PARAMS: "ssl=true"
  #     ports:
  #       - 8080:8080
  #     depends_on:
  #       - postgres
  #     command: start-dev